baseURL = "https://ysoseri1224.github.io/Blog/"
title = "My Hugo Blog"
theme = "PaperMod"

[params]
  author = "Ysoseri1224"
  dateFormat = "2006-01-02"
  highlightStyle = "monokai"
  pygmentsUseClasses = true
